### PR TITLE
Update moode_source_tree.md

### PR DESCRIPTION
**Pull request by janiversen**
Updated the source tree documentation to the best of my abilities (which at the moment does not say a lot).

At least the structure correspond to the current structure, but the text might lack some extra punch.

Architecture doc. is in writing and will be converted to a PR soon.

### CODE REVIEW

**Comment by janiversen** [comment]
Let me close this as well, sorry for disturbing.

**Comment by moodeaudio** [comment]
I haven't had the time to review yet so no need to close it.

**Comment by janiversen** [comment]
I am aware, but to be honest I got enough cold water in the other PR. 

I see quite a potential in this project, it is well known with a good reputation apart from development. When looking at github insight it tells a story less than than 5 committers have made more than 10 commits over 6 year's.

Unless I have misunderstood your attitude completely (I am NOT saying it is a bad attitude) it seems better for both of us if I stop disturbing you.

**Comment by moodeaudio** [comment]
Yes I would say you have completely misunderstood my interactions.

All that matters to me is the quality of the contributions not how many devs or PR's or commits there are. The fact is that only a few devs made the major code contributions to moOde many/most of which were proxied by me into commits.

Git statistics, at least for this project are about as useful as Twitter followers.

**Comment by janiversen** [comment]
Got your point and let's agree to disagree.

I use the statistics as a guideline to see how open a project is (there are several studies showing the relationship). I like the job of growing the committer base, seeing a project grow is a reward in itself.

Nothing wrong in a project being lead by a single person ! it's just not my kind of project for obvious reasons.

I am sorry if I offended you, seems so, and I apologize for that. My intention was only to help, starting with a few small PR, to get a feeling of the project.

**Pull request closed without merging**
